"""JSON Schema (Draft 2020-12) export for Phase 0 core objects.

Kept concise — one file per top-level object would be easier to consume,
but for the walking skeleton a single combined schema with $defs is enough
and gets checked in the tests.
"""

from __future__ import annotations

CORE_SCHEMA: dict = {
    "$schema": "https://json-schema.org/draft/2020-12/schema",
    "$id": "https://verity.dev/schemas/core.v1.json",
    "title": "Verity Phase 0 core schema",
    "type": "object",
    "$defs": {
        "severity": {"enum": ["low", "medium", "high", "critical"]},
        "engine": {"enum": ["prompt", "skill"]},
        "location": {
            "type": "object",
            "required": ["fileId", "artifactPath", "fileDigest", "locationSchemaVersion"],
            "properties": {
                "fileId": {"type": "string"},
                "artifactPath": {"type": "string"},
                "fileDigest": {"type": "string"},
                "sourceEncoding": {"type": "string"},
                "sourceByteRange": {
                    "type": "object",
                    "required": ["start", "end"],
                    "properties": {
                        "start": {"type": "integer", "minimum": 0},
                        "end": {"type": "integer", "minimum": 0},
                    },
                    "additionalProperties": False,
                },
                "structuralPath": {"type": ["string", "null"]},
                "displayLineColumn": {"type": ["object", "null"]},
                "locationSchemaVersion": {"type": "string"},
            },
            "additionalProperties": False,
        },
        "artifactFile": {
            "type": "object",
            "required": ["fileId", "normalizedPath", "size", "status"],
            "properties": {
                "fileId": {"type": "string"},
                "normalizedPath": {"type": "string"},
                "size": {"type": "integer", "minimum": 0},
                "contentDigest": {"type": ["string", "null"]},
                "status": {"enum": ["included", "skipped", "rejected"]},
                "reasonCode": {"type": ["string", "null"]},
                "executable": {"type": "boolean"},
                "symlinkTarget": {"type": ["string", "null"]},
                "raceDetected": {"type": "boolean"},
                "entryType": {"enum": ["file", "symlink", "special", "directory"]},
            },
            "additionalProperties": False,
        },
        "snapshot": {
            "type": "object",
            "required": ["artifactId", "snapshotId", "snapshotManifestDigest",
                         "contentRootDigest", "files", "digestAlgorithm",
                         "canonicalizationVersion"],
            "properties": {
                "artifactId": {"type": "string"},
                "snapshotId": {"type": "string"},
                "snapshotManifestDigest": {"type": "string"},
                "contentRootDigest": {"type": "string"},
                "digestAlgorithm": {"const": "sha256"},
                "canonicalizationVersion": {"type": "string"},
                "files": {"type": "array", "items": {"$ref": "#/$defs/artifactFile"}},
                "promptKind": {
                    "oneOf": [
                        {"type": "null"},
                        {"enum": ["user_prompt", "system_prompt"]}
                    ]
                },
                "artifactRootName": {"type": ["string", "null"],
                                     "minLength": 1, "maxLength": 255},
            },
            "additionalProperties": False,
        },
        "evidence": {
            "type": "object",
            "required": ["evidenceId", "snapshotId", "kind", "locations",
                         "sensitivity", "occurrenceFingerprint", "producer",
                         "derivedFromEvidenceIds", "identityPolicyId", "metadata"],
            "properties": {
                "evidenceId": {"type": "string"},
                "snapshotId": {"type": "string"},
                "kind": {"enum": ["source_span", "parsed_fact", "reference_path",
                                   "dataflow_path", "capability_observation"]},
                "locations": {"type": "array", "items": {"$ref": "#/$defs/location"}},
                "sensitivity": {"enum": ["normal", "sensitive", "secret"]},
                "occurrenceFingerprint": {"type": "string"},
                "producer": {
                    "type": "object",
                    "required": ["componentId", "componentVersion", "executionId"],
                    "properties": {
                        "componentId": {"type": "string"},
                        "componentVersion": {"type": "string"},
                        "executionId": {"type": "string"},
                    },
                    "additionalProperties": False,
                },
                "derivedFromEvidenceIds": {"type": "array", "items": {"type": "string"}},
                "identityPolicyId": {"type": "string"},
                "redactedPreview": {"type": ["string", "null"]},
                "metadata": {"type": "object"},
            },
            "additionalProperties": False,
        },
        "ruleMatch": {
            "type": "object",
            "required": ["eventId", "snapshotId", "ruleId", "ruleVersion",
                         "evidenceIds", "eventDedupKey", "executionId"],
            "properties": {
                "eventId": {"type": "string"},
                "snapshotId": {"type": "string"},
                "ruleId": {"type": "string"},
                "ruleVersion": {"type": "string"},
                "evidenceIds": {"type": "array", "items": {"type": "string"}, "minItems": 1},
                "eventDedupKey": {"type": "string"},
                "executionId": {"type": "string"},
            },
            "additionalProperties": False,
        },
        "candidate": {
            "type": "object",
            "required": ["candidateId", "snapshotId", "findingType", "subject",
                         "claim", "evidenceIds", "falsificationQuestion",
                         "proposedSeverity", "generatorExecutionId",
                         "generatorId", "generatorVersion"],
            "properties": {
                "candidateId": {"type": "string"},
                "snapshotId": {"type": "string"},
                "findingType": {"type": "string"},
                "subject": {"type": "object"},
                "claim": {"type": "string"},
                "evidenceIds": {"type": "array", "items": {"type": "string"}},
                "falsificationQuestion": {"type": "string"},
                "proposedSeverity": {"$ref": "#/$defs/severity"},
                "generatorExecutionId": {"type": "string"},
                "generatorId": {"type": "string"},
                "generatorVersion": {"type": "string"},
            },
            "additionalProperties": False,
        },
        "validationRecord": {
            "type": "object",
            "required": ["validationId", "candidateId", "executionId",
                         "checkedEvidenceIds", "validatorId", "validatorVersion",
                         "status"],
            "properties": {
                "validationId": {"type": "string"},
                "candidateId": {"type": "string"},
                "executionId": {"type": "string"},
                "checkedEvidenceIds": {"type": "array", "items": {"type": "string"}},
                "validatorId": {"type": "string"},
                "validatorVersion": {"type": "string"},
                "status": {"enum": ["completed", "failed", "cancelled"]},
                "verdict": {"enum": ["confirmed", "rejected", "insufficient_evidence"]},
                "rationale": {"type": ["string", "null"]},
                "errorCode": {"type": ["string", "null"]},
                "terminationReason": {"type": ["string", "null"]},
                "evidenceSufficiencyChallenge": {"type": ["object", "null"]},
                "timestamp": {"type": "string"},
            },
            "additionalProperties": False,
        },
        "candidateAssessment": {
            "type": "object",
            "required": ["candidateAssessmentId", "candidateId",
                         "validationPolicyId", "validationPolicyVersion",
                         "validationIds", "state", "reasonCodes"],
            "properties": {
                "candidateAssessmentId": {"type": "string"},
                "candidateId": {"type": "string"},
                "validationPolicyId": {"type": "string"},
                "validationPolicyVersion": {"type": "string"},
                "validationIds": {"type": "array", "items": {"type": "string"}},
                "state": {"enum": ["pending", "confirmed", "rejected",
                                    "insufficient_evidence", "validation_failed"]},
                "reasonCodes": {"type": "array", "items": {"type": "string"}},
            },
            "additionalProperties": False,
        },
        "finding": {
            "type": "object",
            "required": ["findingId", "snapshotId", "findingOccurrenceFingerprint",
                         "findingType", "subject", "subjectKey", "claim",
                         "severity", "origin", "evidenceIds", "controls", "tags"],
            "properties": {
                "findingId": {"type": "string"},
                "snapshotId": {"type": "string"},
                "findingOccurrenceFingerprint": {"type": "string"},
                "findingType": {"type": "string"},
                "subject": {"type": "object"},
                "subjectKey": {"type": "string"},
                "claim": {"type": "string"},
                "severity": {"$ref": "#/$defs/severity"},
                "origin": {
                    "oneOf": [
                        {
                            "type": "object",
                            "required": ["kind", "ruleMatchEventIds"],
                            "properties": {
                                "kind": {"const": "deterministic_rule"},
                                "ruleMatchEventIds": {"type": "array", "items": {"type": "string"}},
                            },
                            "additionalProperties": False,
                        },
                        {
                            "type": "object",
                            "required": ["kind", "candidateId", "candidateAssessmentId", "validationIds"],
                            "properties": {
                                "kind": {"const": "semantic_validation"},
                                "candidateId": {"type": "string"},
                                "candidateAssessmentId": {"type": "string"},
                                "validationIds": {"type": "array", "items": {"type": "string"}},
                            },
                            "additionalProperties": False,
                        }
                    ]
                },
                "evidenceIds": {"type": "array", "items": {"type": "string"}},
                "controls": {"type": "array", "items": {"type": "string"}},
                "tags": {"type": "array", "items": {"type": "string"}},
            },
            "additionalProperties": False,
        },
        "analysisPlanItem": {
            "type": "object",
            "required": ["planItemId", "componentKind", "componentId",
                         "componentVersion", "scope", "requirement", "gatingClass"],
            "properties": {
                "planItemId": {"type": "string"},
                "componentKind": {"enum": ["parser", "analyzer", "rule",
                                            "candidate_generator", "validator"]},
                "componentId": {"type": "string"},
                "componentVersion": {"type": "string"},
                "scope": {"type": "array", "items": {"type": "string"}},
                "requirement": {"enum": ["required", "optional"]},
                "gatingClass": {"enum": ["critical", "normal"]},
            },
            "additionalProperties": False,
        },
        "executionRecord": {
            "type": "object",
            "required": ["executionId", "planItemId", "status",
                         "coveredScopes", "skippedScopes"],
            "properties": {
                "executionId": {"type": "string"},
                "planItemId": {"type": "string"},
                "status": {"enum": ["completed", "partial", "failed", "cancelled",
                                     "unsupported", "not_applicable",
                                     "blocked_by_upstream_failure"]},
                "coveredScopes": {"type": "array", "items": {"type": "string"}},
                "skippedScopes": {"type": "array", "items": {"type": "object"}},
                "reasonCode": {"type": ["string", "null"]},
            },
            "additionalProperties": False,
        },
        "coverageAssessment": {
            "type": "object",
            "required": ["coverageAssessmentId", "reviewId", "reviewPlanId",
                         "reviewPlanRevision", "status", "criticalGapPlanItemIds",
                         "reasonCodes", "policyId", "policyVersion"],
            "properties": {
                "coverageAssessmentId": {"type": "string"},
                "reviewId": {"type": "string"},
                "reviewPlanId": {"type": "string"},
                "reviewPlanRevision": {"type": "integer"},
                "status": {"enum": ["sufficient", "insufficient", "failed"]},
                "criticalGapPlanItemIds": {"type": "array", "items": {"type": "string"}},
                "reasonCodes": {"type": "array", "items": {"type": "string"}},
                "policyId": {"type": "string"},
                "policyVersion": {"type": "string"},
            },
            "additionalProperties": False,
        },
        "reviewPlan": {
            "type": "object",
            "required": ["reviewPlanId", "reviewId", "revision", "phase",
                         "expansionDepth", "items"],
            "properties": {
                "reviewPlanId": {"type": "string"},
                "reviewId": {"type": "string"},
                "revision": {"type": "integer"},
                "phase": {"enum": ["initial", "expanded"]},
                "expansionDepth": {"type": "integer", "maximum": 5},
                "items": {"type": "array", "items": {"$ref": "#/$defs/analysisPlanItem"}},
            },
            "additionalProperties": False,
        },
        "findingMatchRecord": {
            "type": "object",
            "required": ["findingMatchId", "baselineScopeId", "previousSnapshotId",
                         "currentSnapshotId", "previousFindingIds",
                         "currentFindingIds", "state", "method",
                         "matcherPolicyId", "matcherPolicyVersion", "reasonCodes"],
            "properties": {
                "findingMatchId": {"type": "string"},
                "baselineScopeId": {"type": "string"},
                "previousSnapshotId": {"type": "string"},
                "currentSnapshotId": {"type": "string"},
                "previousFindingIds": {"type": "array", "items": {"type": "string"}},
                "currentFindingIds": {"type": "array", "items": {"type": "string"}},
                "state": {"enum": ["new", "existing", "changed", "resolved",
                                    "regressed", "ambiguous",
                                    "unknown_due_to_coverage"]},
                "method": {"enum": ["exact", "stable_subject", "rule_migration", "heuristic"]},
                "matcherPolicyId": {"type": "string"},
                "matcherPolicyVersion": {"type": "string"},
                "reasonCodes": {"type": "array", "items": {"type": "string"}},
            },
            "additionalProperties": False,
        },
        "patchEdit": {
            "type": "object",
            "required": ["operation", "filePath", "baseFileDigest",
                         "sourceEncoding", "sourceByteRange",
                         "expectedRangeDigest", "replacement"],
            "properties": {
                "operation": {"const": "replace"},
                "filePath": {"type": "string"},
                "baseFileDigest": {"type": "string"},
                "sourceEncoding": {"type": "string"},
                "sourceByteRange": {"type": "object"},
                "expectedRangeDigest": {"type": "string"},
                "replacement": {"type": "string"},
            },
            "additionalProperties": False,
        },
        "patchSetProposal": {
            "type": "object",
            "required": ["patchSetId", "proposalDigest", "baseSnapshotId",
                         "baseContentRootDigest", "sourceFindingIds",
                         "applyMode", "edits", "status"],
            "properties": {
                "patchSetId": {"type": "string"},
                "proposalDigest": {"type": "string"},
                "baseSnapshotId": {"type": "string"},
                "baseContentRootDigest": {"type": "string"},
                "sourceFindingIds": {"type": "array", "items": {"type": "string"}},
                "applyMode": {"enum": ["independent", "transactional_all_or_none"]},
                "edits": {"type": "array", "items": {"$ref": "#/$defs/patchEdit"}},
                "status": {"const": "proposed"},
            },
            "additionalProperties": False,
        },
    },
}


def export_schema() -> dict:
    return CORE_SCHEMA
